apps/cart/urls.py
from django.urls import path

from apps.cart import views

app_name: str = "cart"


urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:product_id>/", views.cart_remove, name="cart_remove"),
]

apps/shop/urls.py
from django.urls import path

from apps.shop import views

app_name: str = "shop"


urlpatterns = [
    path("", views.product_list, name="product_list"),
    path("search/", views.product_search, name="search"),
    path("<slug:category_slug>/", views.product_list, name="product_list_by_category"),
    path("<int:id>/<slug:slug>/", views.product_detail, name="product_detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("orders/", include("apps.orders.urls", namespace="orders")),
    path("cart/", include("apps.cart.urls", namespace="cart")),
    path("account/", include("apps.account.urls")),
    path("payment/", include("apps.payment.urls", namespace="payment")),
    path("coupons/", include("apps.coupons.urls", namespace="coupons")),
    path("", include("apps.shop.urls", namespace="shop")),
    path("social-auth/", include("social_django.urls", namespace="social")),
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/shop/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Category(models.Model):
    """
    Model representing a product category.

    Attributes:
        name (str): The name of the category.
        slug (str): The unique slug for the category.

    Meta:
        ordering (tuple): The default sorting for the model.
        verbose_name (str): The human-readable name for a single object.
        verbose_name_plural (str): The human-readable name for multiple objects.
    """

    name: str = models.CharField(max_length=255, db_index=True)
    slug: str = models.SlugField(max_length=255, unique=True)

    class Meta:
        ordering: tuple = ("name",)
        verbose_name: str = "Category"
        verbose_name_plural: str = "Categories"

    def __str__(self) -> str:
        """
        String representation of the category object.
        """
        return self.name

    def get_absolute_url(self) -> str:
        """
        Returns the URL to access a particular category instance.
        """
        return reverse("shop:product_list_by_category", args=[self.slug])


class Product(models.Model):
    """
    Model representing a product.

    Attributes:
        category (Category): The category to which the product belongs.
        name (str): The name of the product.
        slug (str): The unique slug for the product.
        image (ImageField): The image associated with the product.
        description (str): The description of the product.
        price (Decimal): The price of the product.
        available (bool): Whether the product is available or not.
        created (DateTimeField): The date and time the product was created.
        updated (DateTimeField): The date and time the product was last updated.

    Meta:
        ordering (tuple): The default sorting for the model.
        index_together (tuple): A list of two-tuples specifying which fields to index together.

    Methods:
        get_absolute_url(): Returns the URL to access a detail record for this product.
    """

    category: Category = models.ForeignKey(Category, related_name="products", on_delete=models.CASCADE)
    name: str = models.CharField(max_length=255, db_index=True)
    slug: str = models.SlugField(max_length=255, db_index=True)
    image: models.ImageField = models.ImageField(upload_to="products/%Y/%m/%d", blank=True)
    description: str = models.TextField(blank=True)
    price: models.DecimalField = models.DecimalField(max_digits=10, decimal_places=2)
    available: bool = models.BooleanField(default=True)
    created: models.DateTimeField = models.DateTimeField(auto_now_add=True)
    updated: models.DateTimeField = models.DateTimeField(auto_now=True)

    class Meta:
        ordering: tuple = ("name",)
        index_together: tuple = (("id", "slug"),)

    def __str__(self) -> str:
        """
        String representation of the product object.
        """
        return self.name

    def get_absolute_url(self) -> str:
        """
        Returns the URL to access a particular product instance.
        """
        return reverse("shop:product_detail", args=[self.id, self.slug])


class Comment(models.Model):
    """
    Model representing a comment on a product.

    Attributes:
        post (Product): The product being commented on.
        user (User): The user who wrote the comment.
        name (str): The name of the user who wrote the comment.
        email (str): The email of the user who wrote the comment.
        body (str): The content of the comment.
        created (DateTimeField): The date and time the comment was created.
        active (bool): Whether the comment is currently active or not.

    Meta:
        ordering (tuple): The default sorting for the model.

    Methods:
        __str__(): Returns a string representation of the comment,
            including the email of the user who wrote it.
    """

    post: Product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name="comments",
    )
    user: User = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="user")
    name: str = models.CharField(max_length=64)
    email: str = models.EmailField()
    body: str = models.TextField()
    created: models.DateTimeField = models.DateTimeField(auto_now_add=True)
    active: bool = models.BooleanField(default=False)

    class Meta:
        ordering: tuple = ("created",)

    def __str__(self) -> str:
        """
        String representation of the comment object.
        """
        return f"Comment by {self.email}"

apps/shop/forms.py
from django import forms

from apps.shop.models import Comment


class CommentForm(forms.ModelForm):
    """
    A form used for adding comments to a product.

    Attributes:
        Meta (class): The metadata class of the form.
            model (class): The model that the form is associated with.
            fields (tuple): A tuple of fields that the form contains.
    """

    class Meta:
        model: type = Comment
        fields: tuple = ("name", "email", "body")

apps/shop/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render

from apps.cart.forms import CartAddProductForm
from apps.shop.forms import CommentForm
from apps.shop.models import Category, Product


def product_list(request: HttpRequest, category_slug: str = None) -> HttpResponse:
    """
    View that displays the list of available products or products belonging to a specific category.

    Parameters:
    request (HttpRequest): The HTTP request object.
    category_slug (str, optional): The slug of the category to filter by. Defaults to None.

    Returns:
    HttpResponse: The HTTP response object that contains the rendered template.

    """
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(
        request,
        "shop/product/list.html",
        {
            "category": category,
            "categories": categories,
            "products": products,
        },
    )


def product_detail(request: HttpRequest, id: int, slug: str) -> HttpResponse:
    """
    View that displays the details of a specific product, including its comments and allows
        authenticated users to add a comment.

    Parameters:
    request (HttpRequest): The HTTP request object.
    id (int): The id of the product to display.
    slug (str): The slug of the product to display.

    Returns:
    HttpResponse: The HTTP response object that contains the rendered template.

    """
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()

    post = product
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.user.is_authenticated:
        if request.method == "POST":
            comment_form = CommentForm(data=request.POST)
            if comment_form.is_valid:
                new_comment = comment_form.save(commit=False)
                new_comment.post = post
                new_comment.user_id = request.user.id
                new_comment.save()
                return redirect("shop:product_detail", id=id, slug=slug)
        else:
            comment_form = CommentForm()
    else:
        return redirect("login")
    return render(
        request,
        "shop/product/detail.html",
        {
            "product": product,
            "cart_product_form": cart_product_form,
            "comments": comments,
            "new_comment": new_comment,
            "comment_form": comment_form,
        },
    )


def product_search(request: HttpRequest) -> HttpResponse:
    """
    View that searches for products based on a query string and displays the results.

    Parameters:
    request (HttpRequest): The HTTP request object.

    Returns:
    HttpResponse: The HTTP response object that contains the rendered template.

    """
    if request.method == "GET":
        query = request.GET.get("query")
        if query:
            products_search = Product.objects.filter(name__icontains=query)
            return render(
                request,
                "shop/product/list.html",
                {
                    "products_search": products_search,
                    "query": query,
                },
            )
        else:
            return render(request, "shop/product/list.html", {})

apps/shop/templates/shop/base.html
{% load static %}


<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>
        {% block title %}
        Shop
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
    <nav class="bg-white border-gray-200 dark:bg-gray-900">
        <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
            <a href="/" class="flex items-center">
                <img src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600" class="h-8 mr-3" alt="Logo"/>
                <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">The online-shop</span>
            </a>
            <div class="flex md:order-2">
                <form class="form-group relative" action="{% url 'shop:search' %}" method="get">
                    <button type="submit" data-collapse-toggle="navbar-search" aria-controls="navbar-search" aria-expanded="false"
                        class="md:hidden text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-2.5 mr-1">
                        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z" />
                        </svg>
                        <span class="sr-only">Search</span>
                    </button>
                    <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                        <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true"
                            xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z" />
                        </svg>
                        <span class="sr-only">Search icon</span>
                    </div>
                    <input type="text" id="search-navbar"
                        class="block w-full p-2 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                        placeholder="Search..." name="query">
                    <button data-collapse-toggle="navbar-search" type="button"
                        class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
                        aria-controls="navbar-search" aria-expanded="false">
                        <span class="sr-only">Open main menu</span>
                        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M1 1h15M1 7h15M1 13h15" />
                        </svg>
                    </button>
                </form>
            </div>
            
            <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-search">
                <div class="relative mt-3 md:hidden">
                    <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                        <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true"
                            xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z" />
                        </svg>
                    </div>
                    <input type="text" id="search-navbar"
                        class="block w-full p-2 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                        placeholder="Search...">
                </div>
                <ul
                    class="flex flex-col p-4 md:p-0 mt-4 font-medium border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                    <li>
                        <a href="{% url 'dashboard' %}"
                            class="block py-2 pl-3 pr-4 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500"
                            aria-current="page">Dashboard</a>
                    </li>
                
                    <li>
                        <a href="{% url 'cart:cart_detail' %}"
                            class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Cart</a>
                    </li>
                    
                    {% if request.user.is_authenticated %}
                    <li>
                        <a href="{% url 'logout' %}"
                            class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Log out</a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{% url 'login' %}" 
                            class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Log in</a></a>
                    </li>
                    <li>
                        <a href="{% url 'register' %}"
                            class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Sign up</a></a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    

    <div id="content">
        {% block content %}

        {% endblock %}
    </div>
</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.0/flowbite.min.js"></script>
</html>