apps/cart/urls.py
from django.urls import path

from apps.cart import views

app_name: str = "cart"


urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:product_id>/", views.cart_remove, name="cart_remove"),
]

apps/coupons/urls.py
from django.urls import path

from apps.coupons import views

app_name: str = "coupons"


urlpatterns = [
    path("apply/", views.coupon_apply, name="apply"),
]

apps/orders/urls.py
from django.urls import path

from apps.orders import views

app_name: str = "orders"

urlpatterns = [
    path("create/", views.order_create, name="order_create"),
    path("order/<int:order_id>/", views.user_order_detail, name="user_order_detail"),
    path(
        "admin/order/<int:order_id>/",
        views.admin_order_detail,
        name="admin_order_detail",
    ),
    path("admin/order/<int:order_id>/pdf/", views.admin_order_pdf, name="admin_order_pdf"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("orders/", include("apps.orders.urls", namespace="orders")),
    path("cart/", include("apps.cart.urls", namespace="cart")),
    path("account/", include("apps.account.urls")),
    path("payment/", include("apps.payment.urls", namespace="payment")),
    path("coupons/", include("apps.coupons.urls", namespace="coupons")),
    path("", include("apps.shop.urls", namespace="shop")),
    path("social-auth/", include("social_django.urls", namespace="social")),
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/cart/models.py
# Create your models here.

apps/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES: list[tuple[int, str]] = [(i, str(i)) for i in range(1, 12)]


class CartAddProductForm(forms.Form):
    """
    A form used to add a product to the cart.

    Attributes:
    ----------
    quantity : TypedChoiceField
        A field for selecting the quantity of the product to add.
    update : BooleanField
        A field indicating whether to update the quantity of the product
        if it is already in the cart.
    """

    quantity: forms.TypedChoiceField = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update: forms.BooleanField = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

apps/cart/views.py
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST

from apps.cart.cart import Cart
from apps.cart.forms import CartAddProductForm
from apps.coupons.forms import CouponApplyForm
from apps.shop.models import Product


@require_POST
def cart_add(request: HttpRequest, product_id: int) -> HttpResponseRedirect:
    """
    View function to add a product to the cart.

    Args:
        request (HttpRequest): The HTTP request object.
        product_id (int): The ID of the product to add to the cart.

    Returns:
        HttpResponseRedirect: A redirect to the cart detail page.
    """
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd["quantity"], override_quantity=cd["update"])
    return redirect("cart:cart_detail")


def cart_remove(request: HttpRequest, product_id: int) -> HttpResponseRedirect:
    """
    View function to remove a product from the cart.

    Args:
        request (HttpRequest): The HTTP request object.
        product_id (int): The ID of the product to remove from the cart.

    Returns:
        HttpResponseRedirect: A redirect to the cart detail page.
    """
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect("cart:cart_detail")


def cart_detail(request: HttpRequest) -> HttpResponse:
    """
    View function to display the contents of the cart.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponse: The HTTP response object.
    """
    cart = Cart(request)
    coupon_apply_form = CouponApplyForm()
    for item in cart:
        item["update_quantity_form"] = CartAddProductForm(
            initial={"quantity": item["quantity"], "update": True}
        )
    return render(
        request,
        "cart/detail.html",
        {
            "cart": cart,
            "coupon_apply_form": coupon_apply_form,
        },
    )

apps/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
Your shopping cart
{% endblock %}

{% block content %}
<!-- Create By Joker Banny -->
<style>
    @layer utilities {

        input[type="number"]::-webkit-inner-spin-button,
        input[type="number"]::-webkit-outer-spin-button {
            -webkit-appearance: none;
            margin: 0;
        }
    }
</style>

<body>
    <div class="h-screen bg-gray-100 pt-20">
        <h1 class="mb-10 text-center text-2xl font-bold">Cart Items</h1>
        <div class="mx-auto max-w-5xl justify-center px-6 md:flex md:space-x-6 xl:px-0">

            <div class="rounded-lg md:w-2/3">
                {% for item in cart %}
                {% with product=item.product %}
                <div class="justify-between mb-6 rounded-lg bg-white p-6 shadow-md sm:flex sm:justify-start">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}https://png.pngtree.com/png-clipart/20191120/original/pngtree-not-found-outline-icon-vectors-png-image_5053765.jpg{% endif %}"
                        alt="product-image" class="w-10 rounded-lg sm:w-40" />
                    <div class="sm:ml-4 sm:flex sm:w-full sm:justify-between">
                        <div class="mt-5 sm:mt-0">
                            <h2 class="text-lg font-bold text-gray-900">{{ product.name }}</h2>
                        </div>

                        <div class="mt-4 flex justify-between sm:space-y-6 sm:mt-0 sm:block sm:space-x-6">
                            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                {{ item.update_quantity_form.quantity }}
                                {{ item.update_quantity_form.update }}
                                <input type="submit" value="Update">
                                {% csrf_token %}
                            </form>
                            <a href="{% url 'cart:cart_remove' product.id %}">
                                <div class="flex items-center space-x-4">
                                    <p class="text-sm"></p>
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                        stroke-width="1.5" stroke="currentColor"
                                        class="h-5 w-5 cursor-pointer duration-150 hover:text-red-500">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                                    </svg>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
                {% endwith %}
                {% endfor %}
            </div>

            <div class="mt-6 h-full rounded-lg border bg-white p-6 shadow-md md:mt-0 md:w-1/3">
                <div class="mb-2 flex justify-between">
                    <p class="text-gray-700">Subtotal</p>
                    <p class="text-gray-700">${{ cart.get_total_price }}</p>
                </div>
                {% if cart.coupon %}
                <div class="flex justify-between">
                    <p class="text-gray-700">Coupon:</p>
                    <p class="text-gray-700">- ${{ cart.get_discount|floatformat:"2" }}</p>
                </div>
                {% endif %}
                <hr class="my-4" />
                <div class="flex justify-between">
                    <p class="text-lg font-bold">Total</p>
                    <div class="">
                        <p class="mb-1 text-lg font-bold">${{ cart.get_total_price_after_discount|floatformat:"2" }}</p>
                    </div>

                </div>
                <a href="{% url 'orders:order_create' %}">
                <button
                    class="mt-6 w-full rounded-md bg-blue-500 py-1.5 font-medium text-blue-50 hover:bg-blue-600">Check
                    out</button>
                </a>
                <form class="w-full max-w-sm" action="{% url 'coupons:apply' %}" method="post">
                    {% csrf_token %}
                    <div class="flex items-center border-b border-teal-500 py-2">
                        <input
                            class="appearance-none bg-transparent border-none w-full text-gray-700 mr-3 py-1 px-2 leading-tight focus:outline-none"
                            type="text" placeholder="Coupon" aria-label="Full name" name="code">
                        <button
                            class="flex-shrink-0 bg-teal-500 hover:bg-teal-700 border-teal-500 hover:border-teal-700 text-sm border-4 text-white py-1 px-2 rounded"
                            type="submit">
                            Apply
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>
{% endblock %}